// build-theme.mjs — Vite-free theme builder for the Recharge admin.
// Concatenates the single token declaration site (theme.css) + every component
// CSS into one published stylesheet at public/css/rc-admin.css, which
// AdminPanelProvider loads via FilamentAsset::register(Css::make(...)).
//
// Why not Vite/Tailwind: the project path contains Hebrew + spaces, which makes
// the Vite theme pipeline flaky on Windows. The agent brief explicitly sanctions
// shipping the tokens as a plain published CSS file. `npm run build` runs this.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const cssDir = join(root, 'resources/css/filament/admin');
const componentsDir = join(cssDir, 'components');
const outDir = join(root, 'public/css');
const outFile = join(outDir, 'rc-admin.css');

const header = `/* GENERATED by build-theme.mjs — do not edit. Edit resources/css/filament/admin/*. */\n`;
const tokens = readFileSync(join(cssDir, 'theme.css'), 'utf8');
const components = readdirSync(componentsDir)
    .filter((f) => f.endsWith('.css'))
    .sort()
    .map((f) => readFileSync(join(componentsDir, f), 'utf8'))
    .join('\n');

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, header + tokens + '\n' + components + '\n', 'utf8');
console.log('Built public/css/rc-admin.css');
