<?php

namespace App\Domain\Upsell\Holds;

use App\Domain\Upsell\Models\UpsellOrderHold;
use App\Domain\Upsell\Models\UpsellSetting;
use App\Models\Shop;
use App\Services\Shopify\ShopifyClientFactory;
use App\Support\Tenant;
use Illuminate\Support\Facades\Log;

/**
 * Hold a paid order briefly so the shopper can still add to it, then let it go.
 *
 * SCOPE. Only orders that were actually SHOWN an offer are held. A blanket delay
 * on every order in the store would be a fulfillment regression dressed up as a
 * feature, and it would punish the shoppers who were never offered anything.
 *
 * THE EXCLUSIONS ARE THE LOAD-BEARING PART. Four kinds of order must never enter
 * this queue, and one of them is a scar:
 *
 *   - an INSTALLMENTS order under fulfillment lock. Its hold means "not paid
 *     for yet" and is released only at full payment. Releasing it on an upsell
 *     timer ships goods nobody has finished paying for.
 *   - a GIFT order. Given, not sold; there is no upsell to wait for.
 *   - a RECURRING CYCLE order. Generated by us on a schedule, with no shopper
 *     sitting in front of a thank-you page.
 *   - an UPSELL CHILD order. Holding the product of an upsell to wait for an
 *     upsell is a loop.
 *
 * The guard reads the fulfillment_lock METAFIELD, not the tag: a merchant can
 * edit tags by hand, and the metafield is the engine's own record.
 *
 * Releasing NEVER creates a fulfillment. FulfillmentLockService::release() does,
 * with notifyCustomer, which would email "your order shipped" the moment a
 * window closed. Here the hold is simply lifted and the merchant's normal
 * fulfillment flow resumes.
 */
final class OrderHoldService
{
    // === CONSTANTS ===
    /** Shopify's own reason vocabulary for a fulfillment-order hold. */
    private const HOLD_REASON = 'AWAITING_PAYMENT';

    private const MUTATION_HOLD = <<<'GQL'
    mutation letsHold($id: ID!, $reason: FulfillmentHoldReason!, $note: String) {
        fulfillmentOrderHold(id: $id, fulfillmentHold: { reason: $reason, reasonNotes: $note }) {
            fulfillmentHold { id }
            userErrors { field message }
        }
    }
    GQL;

    private const MUTATION_RELEASE = <<<'GQL'
    mutation letsRelease($id: ID!) {
        fulfillmentOrderReleaseHold(id: $id) {
            fulfillmentOrder { id status }
            userErrors { field message }
        }
    }
    GQL;

    /**
     * Start the window for one order, or record why we did not.
     *
     * Idempotent by construction: the table has UNIQUE(shop_id, order) and a
     * second impression on the same order finds the existing row. The window
     * started when the offer was FIRST shown; a shopper reloading the thank-you
     * page must not be able to extend it.
     */
    public function hold(Shop $shop, string $externalOrderId, UpsellSetting $settings): ?UpsellOrderHold
    {
        if ($externalOrderId === '' || ! $settings->holdEnabled()) {
            return null;
        }

        return Tenant::run($shop, function () use ($shop, $externalOrderId, $settings): ?UpsellOrderHold {
            $existing = UpsellOrderHold::query()->where('external_order_id', $externalOrderId)->first();
            if ($existing !== null) {
                return $existing;
            }

            $platform = $shop->platform === Shop::PLATFORM_WOOCOMMERCE
                ? UpsellOrderHold::PLATFORM_WOOCOMMERCE
                : UpsellOrderHold::PLATFORM_SHOPIFY;

            $skip = $this->exclusionFor($shop, $externalOrderId, $platform);
            if ($skip !== null) {
                return $this->record($externalOrderId, $platform, $settings, UpsellOrderHold::STATUS_SKIPPED, [], $skip);
            }

            $refs = $platform === UpsellOrderHold::PLATFORM_SHOPIFY
                ? $this->placeShopifyHold($shop, $externalOrderId)
                : [];

            if ($platform === UpsellOrderHold::PLATFORM_SHOPIFY && $refs === []) {
                // Nothing to hold (digital-only, already fulfilled, or Shopify
                // refused). Recording the reason beats a silent no-op.
                return $this->record(
                    $externalOrderId, $platform, $settings,
                    UpsellOrderHold::STATUS_SKIPPED, [], UpsellOrderHold::SKIP_NO_FULFILLMENT,
                );
            }

            return $this->record($externalOrderId, $platform, $settings, UpsellOrderHold::STATUS_HELD, $refs);
        });
    }

    /**
     * Let one order go. Idempotent: an already-released row is a no-op success,
     * because a scanner that overlaps itself must not double-release.
     */
    public function release(Shop $shop, UpsellOrderHold $hold): bool
    {
        if (! $hold->isHeld()) {
            return true;
        }

        return Tenant::run($shop, function () use ($shop, $hold): bool {
            if ($hold->platform === UpsellOrderHold::PLATFORM_SHOPIFY) {
                foreach ((array) $hold->hold_refs as $fulfillmentOrderGid) {
                    $this->releaseShopifyHold($shop, (string) $fulfillmentOrderGid);
                }

                $this->untag($shop, (string) $hold->external_order_id);
            }

            $hold->forceFill([
                'status' => UpsellOrderHold::STATUS_RELEASED,
                'released_at' => now(),
            ])->save();

            return true;
        });
    }

    // === Exclusions ===

    /**
     * Which of the four never-hold kinds this order is, or null.
     *
     * WooCommerce orders are excluded by the caller's own context (the plugin
     * knows what it created), so only the Shopify order needs interrogating.
     */
    private function exclusionFor(Shop $shop, string $orderId, string $platform): ?string
    {
        if ($platform !== UpsellOrderHold::PLATFORM_SHOPIFY) {
            return null;
        }

        try {
            $order = ShopifyClientFactory::for($shop)->fetchOrderWithMetafields($orderId);
        } catch (\Throwable $e) {
            Log::warning('upsell.hold.order_unreadable', ['shop_id' => $shop->getKey(), 'message' => $e->getMessage()]);

            // Fail CLOSED: an order we cannot read is an order we must not hold.
            // A missed upsell window costs a possible sale; holding an
            // installments order by mistake ships unpaid goods.
            return UpsellOrderHold::SKIP_PLATFORM_REFUSED;
        }

        if ($order === []) {
            return UpsellOrderHold::SKIP_PLATFORM_REFUSED;
        }

        // The METAFIELD, not the tag: a merchant can edit tags by hand, and this
        // is the engine's own record of "not paid for yet".
        if ($this->metafieldIsTrue($order, (string) config('shopify.metafields.fulfillment_lock', 'fulfillment_lock'))) {
            return UpsellOrderHold::SKIP_INSTALLMENTS_HOLD;
        }

        $tags = $this->tagsOf($order);
        $configured = (array) config('shopify.tags');

        foreach ([
            UpsellOrderHold::SKIP_INSTALLMENTS_HOLD => $configured['installments_hold'] ?? '',
            UpsellOrderHold::SKIP_GIFT => $configured['gift_order'] ?? '',
            UpsellOrderHold::SKIP_RECURRING => $configured['recurring_order'] ?? '',
            UpsellOrderHold::SKIP_UPSELL_CHILD => $configured['upsell_child'] ?? '',
        ] as $reason => $tag) {
            if ($tag !== '' && in_array($tag, $tags, true)) {
                return $reason;
            }
        }

        return null;
    }

    // === Shopify mechanics ===

    /**
     * Place a real hold Shopify shows the merchant in Admin, on every fulfilment
     * order that can still take one.
     *
     * @return list<string> the fulfillment-order gids we held
     */
    private function placeShopifyHold(Shop $shop, string $orderId): array
    {
        $client = ShopifyClientFactory::for($shop);
        $held = [];

        try {
            foreach ($client->fetchOrderFulfillmentOrders($orderId) as $fulfillmentOrder) {
                $id = (string) ($fulfillmentOrder['id'] ?? '');
                $status = strtoupper((string) ($fulfillmentOrder['status'] ?? ''));
                if ($id === '' || ! in_array($status, ['OPEN', 'SCHEDULED'], true)) {
                    continue;
                }

                $gid = str_starts_with($id, 'gid://') ? $id : 'gid://shopify/FulfillmentOrder/'.$id;

                $result = $client->graphql(self::MUTATION_HOLD, [
                    'id' => $gid,
                    'reason' => self::HOLD_REASON,
                    'note' => (string) __('upsell.hold.note'),
                ]);

                $errors = $result['data']['fulfillmentOrderHold']['userErrors'] ?? [];
                if ($errors !== []) {
                    Log::warning('upsell.hold.refused', ['shop_id' => $shop->getKey(), 'errors' => $errors]);

                    continue;
                }

                $held[] = $gid;
            }

            if ($held !== []) {
                $this->tag($shop, $orderId);
            }
        } catch (\Throwable $e) {
            Log::warning('upsell.hold.failed', ['shop_id' => $shop->getKey(), 'message' => $e->getMessage()]);
        }

        return $held;
    }

    private function releaseShopifyHold(Shop $shop, string $fulfillmentOrderGid): void
    {
        try {
            ShopifyClientFactory::for($shop)->graphql(self::MUTATION_RELEASE, ['id' => $fulfillmentOrderGid]);
        } catch (\Throwable $e) {
            // A release that fails is retried by the next scanner pass, because
            // the row stays `held` — which is the whole reason it is a row.
            Log::warning('upsell.hold.release_failed', ['shop_id' => $shop->getKey(), 'message' => $e->getMessage()]);
        }
    }

    /**
     * Add / remove our own hold tag, read-then-merge.
     *
     * updateOrderTags() replaces the list wholesale, so writing only our tag
     * would strip every other mark on the order — including the installments
     * ones another release path depends on.
     */
    private function tag(Shop $shop, string $orderId): void
    {
        $this->rewriteTags($shop, $orderId, add: true);
    }

    private function untag(Shop $shop, string $orderId): void
    {
        $this->rewriteTags($shop, $orderId, add: false);
    }

    private function rewriteTags(Shop $shop, string $orderId, bool $add): void
    {
        $tag = (string) config('shopify.tags.upsell_hold', '');
        if ($tag === '') {
            return;
        }

        try {
            $client = ShopifyClientFactory::for($shop);
            $order = $client->fetchOrderWithMetafields($orderId);
            if ($order === []) {
                return;
            }

            $current = $this->tagsOf($order);
            $next = $add
                ? array_values(array_unique(array_merge($current, [$tag])))
                : array_values(array_diff($current, [$tag]));

            $client->updateOrderTags($orderId, $next);
        } catch (\Throwable $e) {
            Log::warning('upsell.hold.tag_failed', ['shop_id' => $shop->getKey(), 'message' => $e->getMessage()]);
        }
    }

    /** @return list<string> */
    private function tagsOf(array $order): array
    {
        $raw = $order['tags'] ?? '';
        $list = is_array($raw) ? $raw : explode(',', (string) $raw);

        return array_values(array_filter(array_map('trim', $list)));
    }

    private function metafieldIsTrue(array $order, string $key): bool
    {
        foreach ((array) ($order['metafields'] ?? []) as $metafield) {
            if ((string) ($metafield['key'] ?? '') === $key) {
                return filter_var($metafield['value'] ?? false, FILTER_VALIDATE_BOOLEAN);
            }
        }

        return false;
    }

    /** @param list<string> $refs */
    private function record(
        string $orderId,
        string $platform,
        UpsellSetting $settings,
        string $status,
        array $refs = [],
        ?string $skipReason = null,
    ): UpsellOrderHold {
        $hold = new UpsellOrderHold;
        $hold->forceFill([
            'shop_id' => Tenant::id(),
            'platform' => $platform,
            'external_order_id' => $orderId,
            'status' => $status,
            'release_at' => now()->addMinutes($settings->holdWindowMinutes()),
            'released_at' => $status === UpsellOrderHold::STATUS_SKIPPED ? now() : null,
            'hold_refs' => $refs,
            'skip_reason' => $skipReason,
        ])->save();

        return $hold;
    }
}
